Tweak tail to ignore '[2 message since 2019-01-01]' like suffixes

diff --git a/scripts/fb-ensure-sid b/scripts/fb-ensure-sid
--- a/scripts/fb-ensure-sid
+++ b/scripts/fb-ensure-sid
@@ -32,7 +32,7 @@ then
 	
 	if [ $result -gt 0 ]
 	then
-	  echo "Login failed. Please update fritzUser and fritzPwd in $HOME/.fritz.config" >&2
+	  echo "Login failed. Please update fritzUser and fritzPwd (E.g. in '${fritzConfig}')" >&2
 	  exit 1
 	fi
 fi
